### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [RoboAlegria/RoboAlegria#16]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by AlfonsoCalero** [comment]
Si esta activo. Yo mismo estoy construyendolo. Se que hay una nueva version para Tablet, pero no he encontrado los archivos actualizados.

Tienes informacion sobre mi versión, con algunos extras en:

https://robotsimpresion3d.wordpress.com/2021/06/30/joy-robot-robo-da-alegria/

Tambien me gustaria invitarte a nuestro grupo de robotica de telegram donde compartimos conocimiento sobre este y otros robots:

https://t.me/Robotica3D

**Comment by ghost** [comment]
Hi AlfonsoCalero.

thank you for feedback.
