### ISSUE TITLE
Bluetooh e Wifi como opcionais

### ISSUE THREAD

**Issue by ferauche** [RoboAlegria/RoboAlegria#2]
Realizar alteraçoes de hardware (no shield) e no código, para deixar a conexão configurável, como uma opção para o usuário utilizar a conexão bluetooth ou wifi.

**Comment by ferauche** [comment]
Aproveitar o novo desenho do shield para receber também os dois motores de passo responsáveis pela movimentação do robô.

**Comment by igorfonseca83** [comment]
Motores adicionados ao shield. Adicionado conector para módulo bluetooth.
